spring:
  application:
    name: restapp
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
logging:
  pattern:
    console: "%c - [%level] - %d - %m%n"